=== cmzwolf/OnlineCodeServlet/WEB-INF/schemas/PDL-TavernaCommunication01.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="JobsList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ServiceName" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="List" type="JobSummary" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="JobSummary">
        <xs:sequence>
            <xs:element name="JobId" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="UserId" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== cmzwolf/OnlineCodeServlet/WEB-INF/schemas/communication01Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobsList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/zwolf/Work/workspaceTestServlet/OnlineCodeServlet/WEB-INF/schemas/PDL-TavernaCommunication01.xsd">
    <ServiceName>http://www.pdl-calc.obspm.fr/montage/</ServiceName>
    <List>
        <JobId>1245</JobId>
        <UserId>22</UserId>
    </List>
    <List>
        <JobId>1284</JobId>
        <UserId>22</UserId>
    </List>
    <List>
        <JobId>1324</JobId>
        <UserId>22</UserId>
    </List>
</JobsList>
