=== cmzwolf/OnlineCodeServlet/WEB-INF/schemas/PDL-TavernaCommunication02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="JobDetail">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="JobId" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="JobPhase" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="DemandDate" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="ProcessingDate" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="FinishingDate" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Inputs" type="Inputs" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Outputs" type="Outputs" minOccurs="0" maxOccurs="1"/>
                <xs:element name="Errors" type="Errors" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="Inputs">
        <xs:sequence>
            <xs:element name="param" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Outputs">
        <xs:sequence>
            <xs:element name="param" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Errors">
        <xs:sequence>
            <xs:element name="ErrorDetail" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Parameter">
        <xs:sequence>
            <xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== cmzwolf/OnlineCodeServlet/WEB-INF/schemas/communication02Example.xml
<?xml version="1.0" encoding="UTF-8"?>
<JobDetail xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/Users/zwolf/Work/workspaceTestServlet/OnlineCodeServlet/WEB-INF/schemas/PDL-TavernaCommunication02.xsd">
    <JobId>1324</JobId>
    <JobPhase>Finished</JobPhase>
    <DemandDate>20/11/2012 09h 52m 45s</DemandDate>
    <ProcessingDate>20/11/2012 09h 54m 45s</ProcessingDate>
    <FinishingDate>20/11/2012 09h 58m 45s</FinishingDate>
    <Inputs>
        <param>
            <Name>Temperature</Name>
            <Value>10000</Value>
        </param>
        <param>
            <Name>Density</Name>
            <Value>10000</Value>
        </param>
    </Inputs>
    <Outputs>
        <param>
            <Name>Volume</Name>
            <Value>15</Value>
        </param>
        <param>
            <Name>Hentalpy</Name>
            <Value>0.3</Value>
        </param>
    </Outputs>
    <Errors>
        <ErrorDetail>PDL-Error : the product Temperature Density must be less than 100000</ErrorDetail>
        <ErrorDetail>PDL-Error : the Temperaturev must be less than 800</ErrorDetail>
    </Errors>
</JobDetail>
